name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++
        
    - name: Configure and build
      run: |
        cmake -B build
        cmake --build build --target rpn_calculator
        
    - name: Test the build
      run: |
        echo "Testing the calculator:"
        ./build/rpn_calculator <<< "5 3 +"
